# Allow use of any pickaxe or force a diamond
# pickaxe to be used
allow-with-any-pickaxe: true

# Cost to use Silk Touch on a mob spawner
# 0 or 0.0 for free
silk-touch-spawner-cost: 0.0

# Show a confirmation when breaking a spawner
# without enough funds (if cost is enabled)
confirm-insufficient-funds: true